// Code generated by main. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/vmware-tanzu/carvel-kapp-controller/pkg/apiserver/apis/datapackaging/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCarvelNoops implements CarvelNoopInterface
type FakeCarvelNoops struct {
	Fake *FakeDataV1alpha1
	ns   string
}

var carvelnoopsResource = schema.GroupVersionResource{Group: "data.packaging.carvel.dev", Version: "v1alpha1", Resource: "carvelnoops"}

var carvelnoopsKind = schema.GroupVersionKind{Group: "data.packaging.carvel.dev", Version: "v1alpha1", Kind: "CarvelNoop"}

// Get takes name of the foo_CarvelNoop, and returns the corresponding foo_CarvelNoop object, and an error if there is any.
func (c *FakeCarvelNoops) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.CarvelNoop, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(carvelnoopsResource, c.ns, name), &v1alpha1.CarvelNoop{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CarvelNoop), err
}

// List takes label and field selectors, and returns the list of CarvelNoops that match those selectors.
func (c *FakeCarvelNoops) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CarvelNoopList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(carvelnoopsResource, carvelnoopsKind, c.ns, opts), &v1alpha1.CarvelNoopList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CarvelNoopList{ListMeta: obj.(*v1alpha1.CarvelNoopList).ListMeta}
	for _, item := range obj.(*v1alpha1.CarvelNoopList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested carvelNoops.
func (c *FakeCarvelNoops) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(carvelnoopsResource, c.ns, opts))

}

// Create takes the representation of a foo_CarvelNoop and creates it.  Returns the server's representation of the foo_CarvelNoop, and an error, if there is any.
func (c *FakeCarvelNoops) Create(ctx context.Context, foo_CarvelNoop *v1alpha1.CarvelNoop, opts v1.CreateOptions) (result *v1alpha1.CarvelNoop, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(carvelnoopsResource, c.ns, foo_CarvelNoop), &v1alpha1.CarvelNoop{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CarvelNoop), err
}

// Update takes the representation of a foo_CarvelNoop and updates it. Returns the server's representation of the foo_CarvelNoop, and an error, if there is any.
func (c *FakeCarvelNoops) Update(ctx context.Context, foo_CarvelNoop *v1alpha1.CarvelNoop, opts v1.UpdateOptions) (result *v1alpha1.CarvelNoop, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(carvelnoopsResource, c.ns, foo_CarvelNoop), &v1alpha1.CarvelNoop{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CarvelNoop), err
}

// Delete takes name of the foo_CarvelNoop and deletes it. Returns an error if one occurs.
func (c *FakeCarvelNoops) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(carvelnoopsResource, c.ns, name), &v1alpha1.CarvelNoop{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCarvelNoops) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(carvelnoopsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.CarvelNoopList{})
	return err
}

// Patch applies the patch and returns the patched foo_CarvelNoop.
func (c *FakeCarvelNoops) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CarvelNoop, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(carvelnoopsResource, c.ns, name, pt, data, subresources...), &v1alpha1.CarvelNoop{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CarvelNoop), err
}
