// Code generated by main. DO NOT EDIT.

package v1alpha1

// CarvelNoopListerExpansion allows custom methods to be added to
// CarvelNoopLister.
type CarvelNoopListerExpansion interface{}

// CarvelNoopNamespaceListerExpansion allows custom methods to be added to
// CarvelNoopNamespaceLister.
type CarvelNoopNamespaceListerExpansion interface{}

// PackageListerExpansion allows custom methods to be added to
// PackageLister.
type PackageListerExpansion interface{}

// PackageNamespaceListerExpansion allows custom methods to be added to
// PackageNamespaceLister.
type PackageNamespaceListerExpansion interface{}

// PackageMetadataListerExpansion allows custom methods to be added to
// PackageMetadataLister.
type PackageMetadataListerExpansion interface{}

// PackageMetadataNamespaceListerExpansion allows custom methods to be added to
// PackageMetadataNamespaceLister.
type PackageMetadataNamespaceListerExpansion interface{}
