// Code generated by main. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	datapackagingv1alpha1 "github.com/vmware-tanzu/carvel-kapp-controller/pkg/apiserver/apis/datapackaging/v1alpha1"
	versioned "github.com/vmware-tanzu/carvel-kapp-controller/pkg/apiserver/client/clientset/versioned"
	internalinterfaces "github.com/vmware-tanzu/carvel-kapp-controller/pkg/apiserver/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/vmware-tanzu/carvel-kapp-controller/pkg/apiserver/client/listers/datapackaging/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CarvelNoopInformer provides access to a shared informer and lister for
// CarvelNoops.
type CarvelNoopInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.CarvelNoopLister
}

type foo_CarvelNoopInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewCarvelNoopInformer constructs a new informer for CarvelNoop type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCarvelNoopInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCarvelNoopInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredCarvelNoopInformer constructs a new informer for CarvelNoop type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCarvelNoopInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DataV1alpha1().CarvelNoops(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DataV1alpha1().CarvelNoops(namespace).Watch(context.TODO(), options)
			},
		},
		&datapackagingv1alpha1.CarvelNoop{},
		resyncPeriod,
		indexers,
	)
}

func (f *foo_CarvelNoopInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCarvelNoopInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *foo_CarvelNoopInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&datapackagingv1alpha1.CarvelNoop{}, f.defaultInformer)
}

func (f *foo_CarvelNoopInformer) Lister() v1alpha1.CarvelNoopLister {
	return v1alpha1.NewCarvelNoopLister(f.Informer().GetIndexer())
}
