// Code generated by main. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/vmware-tanzu/carvel-kapp-controller/pkg/apiserver/apis/datapackaging/v1alpha1"
	scheme "github.com/vmware-tanzu/carvel-kapp-controller/pkg/apiserver/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CarvelNoopsGetter has a method to return a CarvelNoopInterface.
// A group's client should implement this interface.
type CarvelNoopsGetter interface {
	CarvelNoops(namespace string) CarvelNoopInterface
}

// CarvelNoopInterface has methods to work with CarvelNoop resources.
type CarvelNoopInterface interface {
	Create(ctx context.Context, foo_CarvelNoop *v1alpha1.CarvelNoop, opts v1.CreateOptions) (*v1alpha1.CarvelNoop, error)
	Update(ctx context.Context, foo_CarvelNoop *v1alpha1.CarvelNoop, opts v1.UpdateOptions) (*v1alpha1.CarvelNoop, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.CarvelNoop, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.CarvelNoopList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CarvelNoop, err error)
	CarvelNoopExpansion
}

// carvelNoops implements CarvelNoopInterface
type carvelNoops struct {
	client rest.Interface
	ns     string
}

// newCarvelNoops returns a CarvelNoops
func newCarvelNoops(c *DataV1alpha1Client, namespace string) *carvelNoops {
	return &carvelNoops{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the foo_CarvelNoop, and returns the corresponding foo_CarvelNoop object, and an error if there is any.
func (c *carvelNoops) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.CarvelNoop, err error) {
	result = &v1alpha1.CarvelNoop{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("carvelnoops").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CarvelNoops that match those selectors.
func (c *carvelNoops) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CarvelNoopList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.CarvelNoopList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("carvelnoops").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested carvelNoops.
func (c *carvelNoops) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("carvelnoops").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a foo_CarvelNoop and creates it.  Returns the server's representation of the foo_CarvelNoop, and an error, if there is any.
func (c *carvelNoops) Create(ctx context.Context, foo_CarvelNoop *v1alpha1.CarvelNoop, opts v1.CreateOptions) (result *v1alpha1.CarvelNoop, err error) {
	result = &v1alpha1.CarvelNoop{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("carvelnoops").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(foo_CarvelNoop).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a foo_CarvelNoop and updates it. Returns the server's representation of the foo_CarvelNoop, and an error, if there is any.
func (c *carvelNoops) Update(ctx context.Context, foo_CarvelNoop *v1alpha1.CarvelNoop, opts v1.UpdateOptions) (result *v1alpha1.CarvelNoop, err error) {
	result = &v1alpha1.CarvelNoop{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("carvelnoops").
		Name(foo_CarvelNoop.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(foo_CarvelNoop).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the foo_CarvelNoop and deletes it. Returns an error if one occurs.
func (c *carvelNoops) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("carvelnoops").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *carvelNoops) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("carvelnoops").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched foo_CarvelNoop.
func (c *carvelNoops) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CarvelNoop, err error) {
	result = &v1alpha1.CarvelNoop{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("carvelnoops").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
